import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

interface SubjectGrade {
  unitId: string;
  unitName: string;
  score: number;
  grade: string;
  completedMissions: number;
  totalMissions: number;
  averageAccuracy: number;
}

interface GradeReport {
  studentId: string;
  studentName: string;
  period: string;
  subjects: SubjectGrade[];
  overallGrade: string;
  overallScore: number;
  rank?: number;
  totalStudents?: number;
  teacherComment: string;
  attendanceRate: number;
  completionRate: number;
}

interface AttendanceRecord {
  id: string;
  studentId: string;
  studentName: string;
  classId: string;
  date: string;
  status: 'present' | 'late' | 'absent' | 'excused';
  loginTime?: string;
  logoutTime?: string;
  totalActiveMinutes: number;
}

export const generateGradeReportPDF = async (report: GradeReport): Promise<Blob> => {
  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  let y = 20;

  // Add Korean font support (using base64 encoded font)
  // For now, we'll use the default font and romanize Korean text
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(24);

  // Title
  pdf.text('Seongjeopyo (Grade Report)', pageWidth / 2, y, { align: 'center' });
  y += 15;

  // Student Info
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'normal');
  pdf.text(`Student: ${report.studentName}`, 20, y);
  y += 8;
  pdf.text(`Period: ${report.period}`, 20, y);
  y += 8;
  pdf.text(`Date: ${new Date().toLocaleDateString('ko-KR')}`, 20, y);
  y += 15;

  // Overall Grade Box
  pdf.setDrawColor(200);
  pdf.setFillColor(240, 240, 240);
  pdf.roundedRect(20, y, pageWidth - 40, 30, 3, 3, 'FD');

  pdf.setFontSize(18);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Overall Grade', 30, y + 12);
  pdf.setFontSize(32);
  pdf.text(report.overallGrade, pageWidth - 60, y + 22);

  pdf.setFontSize(14);
  pdf.text(`${report.overallScore} points`, pageWidth - 60, y + 12, { align: 'right' });
  y += 40;

  // Statistics
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Statistics:', 20, y);
  y += 8;

  pdf.setFont('helvetica', 'normal');
  const stats = [
    `Attendance Rate: ${report.attendanceRate}%`,
    `Completion Rate: ${report.completionRate}%`,
    `Average Score: ${report.overallScore} points`
  ];

  stats.forEach(stat => {
    pdf.text(stat, 30, y);
    y += 6;
  });
  y += 10;

  // Subject Grades Table
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(14);
  pdf.text('Subject Grades:', 20, y);
  y += 10;

  // Table Header
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'bold');
  pdf.setFillColor(230, 230, 230);
  pdf.rect(20, y - 5, pageWidth - 40, 8, 'F');

  const colWidths = {
    unit: 60,
    progress: 30,
    accuracy: 30,
    score: 25,
    grade: 25
  };

  let x = 20;
  pdf.text('Unit Name', x + 2, y);
  x += colWidths.unit;
  pdf.text('Progress', x + 2, y);
  x += colWidths.progress;
  pdf.text('Accuracy', x + 2, y);
  x += colWidths.accuracy;
  pdf.text('Score', x + 2, y);
  x += colWidths.score;
  pdf.text('Grade', x + 2, y);

  y += 8;

  // Table Rows
  pdf.setFont('helvetica', 'normal');
  report.subjects.forEach((subject, index) => {
    // Check if we need a new page
    if (y > pageHeight - 30) {
      pdf.addPage();
      y = 20;
    }

    // Alternate row colors
    if (index % 2 === 1) {
      pdf.setFillColor(250, 250, 250);
      pdf.rect(20, y - 5, pageWidth - 40, 8, 'F');
    }

    x = 20;
    pdf.text(subject.unitName.substring(0, 30), x + 2, y); // Truncate long names
    x += colWidths.unit;
    pdf.text(`${subject.completedMissions}/${subject.totalMissions}`, x + 2, y);
    x += colWidths.progress;
    pdf.text(`${subject.averageAccuracy}%`, x + 2, y);
    x += colWidths.accuracy;
    pdf.text(`${subject.score}`, x + 2, y);
    x += colWidths.score;
    pdf.setFont('helvetica', 'bold');
    pdf.text(subject.grade, x + 2, y);
    pdf.setFont('helvetica', 'normal');

    y += 8;
  });

  y += 10;

  // Teacher Comment
  if (y > pageHeight - 40) {
    pdf.addPage();
    y = 20;
  }

  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(12);
  pdf.text('Teacher Comment:', 20, y);
  y += 8;

  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(10);
  const commentLines = pdf.splitTextToSize(report.teacherComment, pageWidth - 40);
  commentLines.forEach((line: string) => {
    if (y > pageHeight - 20) {
      pdf.addPage();
      y = 20;
    }
    pdf.text(line, 20, y);
    y += 6;
  });

  // Footer
  pdf.setFontSize(8);
  pdf.setTextColor(150);
  pdf.text(
    `Generated by ISW LMS on ${new Date().toLocaleString('ko-KR')}`,
    pageWidth / 2,
    pageHeight - 10,
    { align: 'center' }
  );

  return pdf.output('blob');
};

export const generateAttendanceReportPDF = async (records: AttendanceRecord[]): Promise<Blob> => {
  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  let y = 20;

  // Title
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(20);
  pdf.text('Attendance Report', pageWidth / 2, y, { align: 'center' });
  y += 15;

  // Date range
  if (records.length > 0) {
    const dates = records.map(r => r.date).sort();
    const startDate = dates[0];
    const endDate = dates[dates.length - 1];

    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'normal');
    pdf.text(`Period: ${startDate} ~ ${endDate}`, pageWidth / 2, y, { align: 'center' });
    y += 10;
  }

  // Statistics
  const present = records.filter(r => r.status === 'present').length;
  const late = records.filter(r => r.status === 'late').length;
  const absent = records.filter(r => r.status === 'absent').length;
  const excused = records.filter(r => r.status === 'excused').length;
  const total = records.length;
  const rate = total > 0 ? Math.round(((present + late) / total) * 100) : 0;

  pdf.setFont('helvetica', 'bold');
  pdf.text('Statistics:', 20, y);
  y += 8;

  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(10);
  const stats = [
    `Present: ${present}`,
    `Late: ${late}`,
    `Absent: ${absent}`,
    `Excused: ${excused}`,
    `Total Days: ${total}`,
    `Attendance Rate: ${rate}%`
  ];

  stats.forEach(stat => {
    pdf.text(stat, 30, y);
    y += 6;
  });
  y += 10;

  // Table Header
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(10);
  pdf.setFillColor(230, 230, 230);
  pdf.rect(20, y - 5, pageWidth - 40, 8, 'F');

  const colWidths = {
    date: 30,
    name: 50,
    status: 30,
    login: 30,
    active: 30
  };

  let x = 20;
  pdf.text('Date', x + 2, y);
  x += colWidths.date;
  pdf.text('Student', x + 2, y);
  x += colWidths.name;
  pdf.text('Status', x + 2, y);
  x += colWidths.status;
  pdf.text('Login Time', x + 2, y);
  x += colWidths.login;
  pdf.text('Active Time', x + 2, y);

  y += 8;

  // Table Rows
  pdf.setFont('helvetica', 'normal');
  records.forEach((record, index) => {
    // Check if we need a new page
    if (y > pageHeight - 20) {
      pdf.addPage();
      y = 20;
    }

    // Alternate row colors
    if (index % 2 === 1) {
      pdf.setFillColor(250, 250, 250);
      pdf.rect(20, y - 5, pageWidth - 40, 8, 'F');
    }

    x = 20;
    pdf.text(record.date, x + 2, y);
    x += colWidths.date;
    pdf.text(record.studentName.substring(0, 20), x + 2, y);
    x += colWidths.name;

    // Status with color
    const statusText = record.status === 'present' ? 'Present' :
                      record.status === 'late' ? 'Late' :
                      record.status === 'absent' ? 'Absent' : 'Excused';
    pdf.text(statusText, x + 2, y);
    x += colWidths.status;

    pdf.text(record.loginTime || '-', x + 2, y);
    x += colWidths.login;

    pdf.text(record.totalActiveMinutes > 0 ? `${record.totalActiveMinutes}m` : '-', x + 2, y);

    y += 8;
  });

  // Footer
  pdf.setFontSize(8);
  pdf.setTextColor(150);
  pdf.text(
    `Generated by ISW LMS on ${new Date().toLocaleString('ko-KR')}`,
    pageWidth / 2,
    pageHeight - 10,
    { align: 'center' }
  );

  return pdf.output('blob');
};

// Helper function to generate share code
export const generateShareCode = (studentId: string, period: string): string => {
  const data = `${studentId}-${period}-${Date.now()}`;
  return btoa(data).replace(/=/g, '').substring(0, 16);
};

// Helper function to decode share code
export const decodeShareCode = (shareCode: string): { studentId: string; period: string } | null => {
  try {
    const decoded = atob(shareCode);
    const parts = decoded.split('-');
    if (parts.length >= 2) {
      return {
        studentId: parts[0],
        period: parts[1]
      };
    }
    return null;
  } catch (error) {
    console.error('Error decoding share code:', error);
    return null;
  }
};
